name: Sync with Original Repo (Dev Branch)

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable GitHub token for this step

      - name: Configure Git
        run: |
          git config user.name "karam14"
          git config user.email "krm-011@hotmail.com"
        
      - name: Add original repo as remote
        run: |
          git remote add upstream https://github.com/Binary-Breakers/Frontend.git
          git fetch upstream
          git checkout dev
          git merge upstream/dev
          
      - name: Push changes to forked repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin dev
